language: java
sudo: required
dist: trusty
jdk:
- oraclejdk10
before_script:
- chmod a+x gradlew
- chmod a+x gradle/wrapper/gradle-wrapper.jar
notifications:
  slack:
    secure: ONchpho+AA1npO34YxPZP4Y9LO7lbv9qni3VaNkNX5hb4/axSunY+uO0c8h3/ZptQbX6kI0kJxiOdScKAChMSXqKKfwo9kfHW7YpdERMQz+CetczK7t+JIiKkqOff/9jv9iwlePoiEFOAGz2Ph/qq7qPFjp76BxVb6/pVHjmQN8+Zq9DwqGSUSaPf4chYt/qiK7c6s+mKDZryUN6B0Bb79s2mLpJDkFBtRaJdii2fs8c0UrvzH2C95fNR+9D215oilhiQHSdFIj5FybanbmaeZbc5v4lbNU6NsKfZs99d3g7cQNtBl/V2rj/nh2/8QbcZ2nZ8+L2f+5TlhxGk1unw0DbeIxntD2YlGvabr3UVZWFVusG5IDzNMWUZslCHJjSrnGVtcN7inz3nOCqqtdj6cp/H2UEbHHmo0SJHMTmAvoklW8jbpEA31yCn1l/xBmg/ECV8/L8Ou0pt7T0SW1twip4F3culm2evvTSX+SCgo1wfFmzdJB3nzrmGsixv9DiryEXU06gAvAJH3Wh4rUJ+JRWruVnTmt2WVKHGBlI/A5QQK52q5wRoAclPn3YYbLPHUQdYVFpgdfiovwkMMfosnO++yKm78vI+9k9YYCmLJ1hRMZCJoM0XWpGVdNrrWNpbfsTQ0Nd/iRik/wRqRBtWAlGPPdbeK3ZkmxF/ZdGK+M=
    
